services:
  - type: web
    name: spirit-sait
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    branch: main
    repo: https://github.com/g0os/Spirit-Sait
